services:
    btn.pdf_manager:
        class: Btn\DealBundle\Model\PdfManager
        arguments:
            webRoot: %web_root%

    btn.deal_manager:
        class: Btn\DealBundle\Model\DealManager
        arguments:
            em:            '@doctrine.orm.entity_manager'
            twig:          null
            pdf:           '@btn.pdf_manager'
            kernelRootDir: %kernel.root_dir%
            paginator:     '@knp_paginator'
            formFactory:   '@form.factory'
            seller:        %deal.seller%
