<?php

namespace Btn\DealBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends EntityRepository
{
    /**
     *
     * Get query from query builder for filters
     *
     * @return query query
     **/
    public function getSearchQuery($conditions)
    {
        $qb = $this->createQueryBuilder('d')
            ->select('d')
            ->add('orderBy', 'd.createdAt DESC');
        ;

        if (!empty($conditions) && is_array($conditions)) {
            $expr = call_user_func_array(array($qb->expr(), 'andx'), $conditions);
            $qb->where($expr);
        }

        return $qb;
    }

    /**
     * undocumented function
     *
     * @return void
     * @author
     **/
    public function getDealsForUser($userId)
    {
        return  $this->getEntityManager()
            ->createQuery('SELECT d FROM Btn\DealBundle\Entity\Deal d WHERE d.ownerId  = :ownerId ORDER BY d.createdAt')
            ->setParameter('ownerId', $userId)
            ->getResult()
        ;
    }
}
